services:
  - type: web
    name: kidsanimation
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Kidsanim@2024
      - key: N8N_HOST
        value: kidsanimation.onrender.com
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://kidsanimation.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: kidsanim32charslongencryptionkey
      - key: TZ
        value: Asia/Kolkata
      - key: NODE_ENV
        value: production
